### ISSUE TITLE
Installation Minipolish

### ISSUE THREAD

**Issue by joanmarticarreras** [rrwick/Minipolish#2]
Dear  @rrwick ,

I decide to take a look to your assembler, after our small Twitter chat. Installed `edlib` and `pytest` and download the tar files to run `minipolish-runner.py` with Python 5.4.0.

So far, I've been unable to test due to this error in `__main__.py`:

```
Traceback (most recent call last): 
                                                                                                                                                                      

File "./minipolish-runner.py", line 18, in <module>                                                                                                                                                

from minipolish.__main__ import main                                                                                                                                                                 
File "/root/work/45/0c2a79ae03f5b21f626abd623c6eb6/Minipolish-0.1.2/minipolish/__main__.py", 
line 106  round_name = f'round_{i+1}'                                                                                                                                                                                                      
^                                                                                                                                                                        
SyntaxError: invalid syntax 
```
What do you think? I am not very proficient with Python. I'd appreciate your help!

Cheers

**Comment by rrwick** [comment]
Sorry - I failed to mention in the README that you'll need Python 3.6 or later for Minipolish. Not sure what version you have, but it will be an earlier one - check with `python3 --version` (it won't be 5.4.0 which doesn't exist).

In case you're curious, it's because I used [f-strings](https://www.python.org/dev/peps/pep-0498/) which are a nice new way of formatting strings in Python, but were only added in v3.6. The syntax error you hit was because your earlier Python encountered that new syntax and didn't know what it was.

I've added the version requirement to the README now - thanks!
